name: Deploy Firefox Extension

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Bump Version (Optional)
      run: python3 bump_version.py
      continue-on-error: true  # skip if you don’t have it

    - name: Build .xpi File
      run: |
        cd my-extension
        zip -r ../my-ext.xpi .

    - name: Upload Firefox Extension
      env:
        AMO_JWT_ISSUER: ${{ secrets.AMO_JWT_ISSUER }}
        AMO_JWT_SECRET: ${{ secrets.AMO_JWT_SECRET }}
      run: python3 upload_extension.py

